name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install pip install Appium-Python-Client
    - name: Running the tunnel
      run: |
        if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
          ./run_lt_linux.sh  # Execute the Linux script
        elif [ ${{ matrix.os }} == 'windows-latest' ]; then
          powershell -File run_lt_windows.ps1  # Execute the Windows PowerShell script
        fi
    - name: Running the Script
      run: python android.py
    
    
